Add L-KaaS docs
SSU-DCN/L-KaaS pull request #1
Opened 2023-03-23 07:22 UTC by ntnguyencse

Add L-KaaS docs

2023-03-27 06:03 UTC, bactp approved these changes

2023-03-29 04:13 UTC, Jangwon-Lee-DCN requested changes
I commented to some files.
IMO, please change design/README.md to explain everything roughly, not just “see something” and add embedded link for detailed like flows and operations. Maybe, a new file is also okay at desgin/something.

2023-03-29 04:13 UTC, Jangwon-Lee-DCN commented on docs/README.md
> +* Cluster API is a project which is a Kubernetes project to bring declarative, Kubernetes-style APIs to cluster creation, configuration, and management but Cluster API still requires complex configur
```suggestion
* Cluster API is a Kubernetes subproject to bring declarative, Kubernetes-style APIs to cluster creation, configuration, and management but Cluster API still requires complex configuration, deep knowledge of Kubernetes, cloud provider, relies on several components being configured correctly to have a working cluster. L-KaaS uses Kubernetes Resources Model and Kubernetes environment to provide an abstraction high-level & automation framework that automates clusters, logical clusters. The L-KaaS is a project standing on the Cluster API project. 
```

2023-03-29 04:13 UTC, Jangwon-Lee-DCN commented on docs/design/diagrams/creating-logical-cluster-diagram.png
A logical cluster is created by EMCO using created clusters on Cloud Provider. So you have to add corresponding block and registration flow to EMCO.

2023-03-29 04:13 UTC, Jangwon-Lee-DCN commented on docs/design/diagrams/functional.png
A Logical cluster can be grouped with Private and Public cloud both. And you should describe the namespaces of the logical cluster. The logical cluster can use clusters for all resources or a specific namespace with a resource quota. Please check and follow EMCO’s DCM documents.

2023-03-29 04:13 UTC, Jangwon-Lee-DCN commented on docs/design/diagrams/reference.png
It’s same. Please change the Cloud Infrastructure block.

2023-03-30 05:44 UTC, ntnguyencse commented
> I commented to some files. IMO, please change design/README.md to explain everything roughly, not just “see something” and add embedded link for detailed like flows and operations. Maybe, a new file is also okay at desgin/something.

I'll add introduction and explanation for each of it.

2023-11-03 06:26 UTC, closed without merging